name: Docker Repo Update
on:
  workflow_call:
    inputs:
      user:
        required: true
        type: string
      pass:
        required: true
        type: string
jobs:
  publish-to-docker:
    runs-on: ubuntu-latest
    environment: Deployment
    steps:
      - name: Check Out Repository Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Retrieve Docker Metadata
        id: meta
        uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96
        with:
          images: ${{ inputs.user }}/pypkipractice
      - name: Log into Docker Hub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          username: ${{ inputs.user }}
          password: ${{ inputs.pass }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5
      - name: Build and Push Docker Image
        uses: docker/build-push-action@b32b51a8eda65d6793cd0494a773d4f6bcef32dc
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}
          provenance: true
          sbom: true
  update-docker-repo-info:
    needs: publish-to-docker
    runs-on: ubuntu-latest
    environment: Deployment
    steps:
      - name: Check Out Repository Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@e98e4d1628a5f3be2be7c231e50981aee98723ae
        with:
          username: ${{ inputs.user }}
          password: ${{ inputs.pass }}
          repository: ${{ inputs.user }}/pypkipractice
          short-description: PKI simulation I created to practice digital certificates and public-key encryption.