name: Testing Pipeline
permissions:
  contents: read
  pull-requests: write
on:
  schedule:
    - cron: '0 17 * * *'
  push:
    tags:
      - '*'
    branches:
      - '*'
jobs:
  tagging-test:
    runs-on: ubuntu-latest
    environment: Test Deployment
    steps:
      - name: Decide on New Tags
        run: |
          if [[ ${{ github.event_name }} == "push" && "${{ github.ref_type }}" == "tag" ]]; then
            echo "tags=laoluade/pypkipractice:latest,laoluade/pypkipractice:${{ github.ref_name }}" >> $GITHUB_ENV
          else
            echo "tags=laoluade/pypkipractice:latest" >> $GITHUB_ENV
          fi
      - name: Print New Tags
        run: echo ${{ env.tags }}
  key-signing-test:
    runs-on: ubuntu-latest
    environment: Test Deployment
    steps:
      - name: Check Out Repository Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Setup Git User
        run: |
          git config --global user.name "Laolu Bot"
          git config --global user.email "${{ vars.EMAIL }}"
      - name: Setup GPG Key
        uses: crazy-max/ghaction-import-gpg@cb9bde2e2525e640591a934b1fd28eef1dcaf5e5
        with:
          gpg_private_key: ${{ secrets.LAOLU_BOT_GPG_PRIVATE_KEY }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: List Keys
        run: |
          gpg --list-secret-keys --keyid-format LONG
          gpg --list-keys --keyid-format LONG
      - name: List Git Config
        run: git config --list --show-origin
  test-project-nox:
    if: github.event.head_commit.author.name != 'Laolu Bot'
    uses: laoluadewoye/PKI_Practice_Python/.github/workflows/nox_test.yml@main
  build-project:
    if: github.event_name == 'push' && github.ref_type == 'tag'
    needs: test-project-nox
    uses: laoluadewoye/PKI_Practice_Python/.github/workflows/pypi_build.yml@main
  publish-to-testpypi:
    needs: build-project
    runs-on: ubuntu-latest
    environment:
      name: Test Deployment
      url: https://test.pypi.org/p/PyPkiPractice
    permissions:
      id-token: write
    steps:
      - name: Retrieve Distribution Artifact
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16
        with:
          name: distribution-packages
          path: dist/
      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@67339c736fd9354cd4f8cb0b744f2b82a74b5c70
        with:
          repository-url: https://test.pypi.org/legacy/