name: Repo Page Update
on:
  workflow_call:
jobs:
  create-html:
    runs-on: ubuntu-latest
    environment: Test Deployment
    permissions:
      contents: write
    steps:
      - name: Check Out Repository Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Setup Pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc
      - name: Setup Git User
        run: |
          git config --global user.name "Laolu Bot"
          git config --global user.email "${{ vars.EMAIL }}"
      - name: Setup GPG Key
        uses: crazy-max/ghaction-import-gpg@cb9bde2e2525e640591a934b1fd28eef1dcaf5e5
        with:
          gpg_private_key: ${{ secrets.LAOLU_BOT_GPG_PRIVATE_KEY }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Setup Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b
        with:
          python-version: 3.12
          cache: pip
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Generate a README HTML File
        run: python -m asciidoc -o docs/index.html README.adoc
      - name: Generate a CONFIG_GUIDE HTML File
        run: pandoc CONFIG_GUIDE.md -o docs/config-guide.html
      - name: Add New HTMLs to Repo
        run: |
          git add docs/index.html docs/config-guide.html
          git commit -S -m "Automated update to Repo Site."
          git push