name: test-to-publish-pipeline
on:
  schedule:
    - cron: '0 12 * * *'
  push:
    tags:
      - '*'
    branches:
      - main
jobs:
  test-project-nox:
    runs-on: ubuntu-latest
    environment: Deployment
    steps:
      - name: Check Out Repository Code
        uses: actions/checkout@v4
      - name: Setup Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Setup Python 3.14 Alpha 3
        uses: actions/setup-python@v5
        with:
          python-version: 3.14.0-alpha.3
      - name: Setup Nox
        uses: fjwillemsen/setup-nox2@v3.0.0
      - name: Run Nox
        run: nox
  build-project:
    needs: test-project-nox
    runs-on: ubuntu-latest
    environment: Deployment
    steps:
      - name: Check Out Repository Code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Build Project
        run: python -m build
      - name: Save Distribution Artifact
        uses: actions/upload-artifact@v4
        with:
          name: distribution-packages
          path: dist/
  publish-to-pypi:
    needs: build-project
    runs-on: ubuntu-latest
    environment:
      name: Deployment
      url: https://pypi.org/p/PyPkiPractice
    permissions:
      id-token: write
    steps:
      - name: Retrieve Distribution Artifact
        uses: actions/download-artifact@v4
        with:
          name: distribution-packages
          path: dist/
      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
  publish-to-docker:
    needs: build-project
    runs-on: ubuntu-latest
    environment: Deployment
    steps:
      - name: Check Out Repository Code
        uses: actions/checkout@v4
      - name: Retrieve Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKERHUB_USERNAME }}/pypkipractice
      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Push Docker Image (Tag Push)
        if: github.event_name == 'push' && github.ref_type == 'tag'
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}
          provenance: true
          sbom: true
      - name: Build and Push Docker Image (Other)
        if: (github.event_name == 'push' && github.ref_type != 'tag') || github.event_name != 'push'
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/pypkipractice:latest
          annotations: ${{ steps.meta.outputs.annotations }}
          provenance: true
          sbom: true