name: test-to-testpublish-pipeline
on:
  schedule:
    - cron: '0 17 * * *'
  push:
    tags:
      - '*'
    branches:
      - '*'
jobs:
  test-project-nox:
    runs-on: ubuntu-latest
    environment: Test Deployment
    steps:
      - name: Check Out Repository Code
        uses: actions/checkout@v4
      - name: Test Project
        uses: laoluadewoye/PKI_Practice_Python/.github/workflows/nox_test.yml@network-dev
  tagging-test:
    needs: test-project-nox
    runs-on: ubuntu-latest
    environment: Test Deployment
    steps:
      - name: Decide on New Tags
        run: |
          if [[ ${{ github.event_name }} == "push" && "${{ github.ref_type }}" == "tag" ]]; then
            echo "tags=laoluade/pypkipractice:latest,laoluade/pypkipractice:${{ github.ref_name }}" >> $GITHUB_ENV
          else
            echo "tags=laoluade/pypkipractice:latest" >> $GITHUB_ENV
          fi
      - name: Print New Tags
        run: echo ${{ env.tags }}
  build-project:
    if: github.event_name == 'push' && github.ref_type == 'tag'
    needs: test-project-nox
    runs-on: ubuntu-latest
    environment: Test Deployment
    steps:
      - name: Check Out Repository Code
        uses: actions/checkout@v4
      - name: Build the Project
        uses: laoluadewoye/PKI_Practice_Python/.github/workflows/pypi_build.yml@network-dev
  publish-to-testpypi:
    needs: build-project
    runs-on: ubuntu-latest
    environment:
      name: Test Deployment
      url: https://test.pypi.org/p/PyPkiPractice
    permissions:
      id-token: write
    steps:
      - name: Retrieve Distribution Artifact
        uses: actions/download-artifact@v4
        with:
          name: distribution-packages
          path: dist/
      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
