name: test-to-publish-pipeline
on:
  schedule:
    - cron: '0 17 * * *'
  push:
    tags:
      - '*'
    branches:
      - main
jobs:
  test-project-nox:
    runs-on: ubuntu-latest
    environment: Test Deployment
    steps:
      - name: Check Out Repository Code
        uses: actions/checkout@v4
      - name: Test Project
        uses: .github/workflows/nox_test.yml
  build-project:
    if: github.event_name == 'push' && github.ref_type == 'tag'
    needs: test-project-nox
    runs-on: ubuntu-latest
    environment: Test Deployment
    steps:
      - name: Check Out Repository Code
        uses: actions/checkout@v4
      - name: Build the Project
        uses: .github/workflows/pypi_build.yml
  publish-to-pypi:
    needs: build-project
    runs-on: ubuntu-latest
    environment:
      name: Deployment
      url: https://pypi.org/p/PyPkiPractice
    permissions:
      id-token: write
    steps:
      - name: Retrieve Distribution Artifact
        uses: actions/download-artifact@v4
        with:
          name: distribution-packages
          path: dist/
      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
  publish-to-docker:
    needs: build-project
    runs-on: ubuntu-latest
    environment: Deployment
    steps:
      - name: Check Out Repository Code
        uses: actions/checkout@v4
      - name: Retrieve Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKERHUB_USERNAME }}/pypkipractice
      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}
          provenance: true
          sbom: true
  update-docker-repo-info:
    needs: publish-to-docker
    runs-on: ubuntu-latest
    environment: Deployment
    steps:
      - name: Check Out Repository Code
        uses: actions/checkout@v4
      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ vars.DOCKERHUB_USERNAME }}/pypkipractice
          short-description: PKI simulation I created to practice digital certificates and public-key encryption.
