name: code-tester
on: push
jobs:
  code-tester-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
      - uses: actions/checkout@v4
      - run: echo "$(pytest Tests)"
