name: test-project
on:
  schedule:
    - cron: '0 12 * * *'
  push:
    branches:
      - main
jobs:
  test-project:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository Code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: 3.12
          cache: pip
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run Tests and Save Results
        run: pytest PKIPractice/tests --junitxml=results.xml
      - name: Upload Test Results as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: results.xml
  update-pypi-if-ready:
    needs: test-project
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve Test Results as Artifact
        uses: actions/download-artifact@v3
        with:
          name: test-results
      - name: Get Error Count
        run: ERRORS=$(awk -F'errors="' '{print $2}' results.xml | awk -F'"' '{print $1}')
      - name: Get Failure Count
        run: FAILURES=$(awk -F'failures="' '{print $2}' results.xml | awk -F'"' '{print $1}')
      - name: Echo Results
        run: |
          echo "Errors: $ERRORS"
          echo "Failures: $FAILURES"
