name: test-project
on:
  schedule:
    - cron: '0 12 * * *'
  push:
    branches:
      - main
jobs:
  test-project:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository Code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: 3.12
          cache: pip
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run Tests
        run: pytest PKIPractice/tests
