name: test-to-publish-pipeline
on:
  schedule:
    - cron: '0 12 * * *'
  push:
    tags:
      - '*'
jobs:
  test-project:
    runs-on: ubuntu-latest
    environment: Deployment
    steps:
      - name: Check Out Repository Code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run Tests
        run: pytest PKIPractice/tests
  build-project:
    needs: test-project
    runs-on: ubuntu-latest
    environment: Deployment
    steps:
      - name: Check Out Repository Code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Build Project
        run: python -m build
      - name: Save Distribution Artifact
        uses: actions/upload-artifact@v4
        with:
          name: distribution-packages
          path: dist/
  publish-to-pypi:
    needs: build-project
    runs-on: ubuntu-latest
    environment:
      name: Deployment
      url: https://pypi.org/p/PyPkiPractice
    permissions:
      id-token: write
    steps:
      - name: Retrieve Distribution Artifact
        uses: actions/download-artifact@v4
        with:
          name: distribution-packages
          path: dist/
      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
  publish-to-docker:
    needs: publish-to-pypi
    runs-on: ubuntu-latest
    environment: Deployment
    steps:
      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            laoluadewoye/pypkipractice:latest
            laoluadewoye/pypkipractice:${{ github.ref_name }}
