name: test-to-testpublish-pipeline
permissions:
  contents: read
  pull-requests: write
on:
  schedule:
    - cron: '0 17 * * *'
  push:
    tags:
      - '*'
    branches:
      - '*'
jobs:
  test-project-nox:
    uses: laoluadewoye/PKI_Practice_Python/.github/workflows/nox_test.yml@main
  tagging-test:
    needs: test-project-nox
    runs-on: ubuntu-latest
    environment: Test Deployment
    steps:
      - name: Decide on New Tags
        run: |
          if [[ ${{ github.event_name }} == "push" && "${{ github.ref_type }}" == "tag" ]]; then
            echo "tags=laoluade/pypkipractice:latest,laoluade/pypkipractice:${{ github.ref_name }}" >> $GITHUB_ENV
          else
            echo "tags=laoluade/pypkipractice:latest" >> $GITHUB_ENV
          fi
      - name: Print New Tags
        run: echo ${{ env.tags }}
  build-project:
    if: github.event_name == 'push' && github.ref_type == 'tag'
    needs: test-project-nox
    uses: laoluadewoye/PKI_Practice_Python/.github/workflows/pypi_build.yml@main
  publish-to-testpypi:
    needs: build-project
    runs-on: ubuntu-latest
    environment:
      name: Test Deployment
      url: https://test.pypi.org/p/PyPkiPractice
    permissions:
      id-token: write
    steps:
      - name: Retrieve Distribution Artifact
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16
        with:
          name: distribution-packages
          path: dist/
      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@67339c736fd9354cd4f8cb0b744f2b82a74b5c70
        with:
          repository-url: https://test.pypi.org/legacy/